In [2]:
# Dependencies
import pandas as pd
import numpy as np
import requests
import json

# Import API key
from config import gkey

In [3]:
# Import cities file into the cities_pd DataFrame
cities_pd = pd.read_csv("../Resources/Cities.csv")
cities_pd.head()

            City         State
0  New York City      New York
1    Los Angeles    California
2        Chicago      Illinois
3        Houston         Texas
4   Philadelphia  Pennsylvania

In [8]:
# Add columns for lat, lng, airport name, airport address, airport rating.
# Hint: Be sure to specify "" as the initial value for each column.
cities_pd['lat'] = ""
cities_pd['lng'] = ""
cities_pd['airport name'] = ""
cities_pd['airport address'] = ""
cities_pd['airport rating'] = ""

cities_pd.head()

,City,State,lat,lng,airport name,airport address,airport rating
0,New York City,New York,,,,,
1,Los Angeles,California,,,,,
2,Chicago,Illinois,,,,,
3,Houston,Texas,,,,,
4,Philadelphia,Pennsylvania,,,,,

In [9]:
# Loop through the cities_pd and get the lat/long for each city
# Hint: `requests.get(target_url).json()`
# Hint: `for index, row in cities_pd.iterrows():`
# Hint: `cities_pd.loc


# Print the json
#print(geo_data)
# json.dumps(geo_data,indent=4)
# lat = geo_data["results"][0]["geometry"]["location"]["lat"]
# lng = geo_data["results"][0]["geometry"]["location"]["lng"]
# print("%s: %s, %s" % (target_city, lat, lng))

# use iterrows to iterate through pandas dataframe
for index, row in cities_pd.iterrows():
    
    # get city & state from df
    city = row['City']
    
    target_url = "https://maps.googleapis.com/maps/api/geocode/json?" \
    "address=%s&key=%s" % (city, gkey)
    
    # Run a request to endpoint and convert result to json
    geo_data = requests.get(target_url).json()
    
    # assemble url and make API request
    print(f"Retrieving Results for Index {index}: {city}.")
#     response = requests.get(target_url).json()
    
#     # extract results
#     results = response['results']
    
    try:
        print(f"Looking for {city} latitude and longitude.")
        cities_pd.loc[index, 'lat'] = geo_data["results"][0]["geometry"]["location"]["lat"]
        cities_pd.loc[index, 'lng'] = geo_data["results"][0]["geometry"]["location"]["lng"]
        
    except (KeyError, IndexError):
        print("Missing field/result... skipping.")
        
    print("------------")

Retrieving Results for Index 0: New York City.
Looking for New York City latitude and longitude.
------------
Retrieving Results for Index 1: Los Angeles.
Looking for Los Angeles latitude and longitude.
------------
Retrieving Results for Index 2: Chicago.
Looking for Chicago latitude and longitude.
------------
Retrieving Results for Index 3: Houston.
Looking for Houston latitude and longitude.
------------
Retrieving Results for Index 4: Philadelphia.
Looking for Philadelphia latitude and longitude.
------------
Retrieving Results for Index 5: Phoenix.
Looking for Phoenix latitude and longitude.
------------
Retrieving Results for Index 6: San Antonio.
Looking for San Antonio latitude and longitude.
------------
Retrieving Results for Index 7: San Diego.
Looking for San Diego latitude and longitude.
------------
Retrieving Results for Index 8: Dallas.
Looking for Dallas latitude and longitude.
------------
Retrieving Results for Index 9: San Jose.
Looking for San Jose latitude and longitude.
------------
Retrieving Results for Index 10: Austin.
Looking for Austin latitude and longitude.
------------
Retrieving Results for Index 11: Jacksonville.
Looking for Jacksonville latitude and longitude.
------------
Retrieving Results for Index 12: San Francisco.
Looking for San Francisco latitude and longitude.
------------
Retrieving Results for Index 13: Indianapolis.
Looking for Indianapolis latitude and longitude.
------------
Retrieving Results for Index 14: Columbus.
Looking for Columbus latitude and longitude.
------------
Retrieving Results for Index 15: Fort Worth.
Looking for Fort Worth latitude and longitude.
------------
Retrieving Results for Index 16: Charlotte.
Looking for Charlotte latitude and longitude.
------------
Retrieving Results for Index 17: Seattle.
Looking for Seattle latitude and longitude.
------------
Retrieving Results for Index 18: Denver.
Looking for Denver latitude and longitude.
------------
Retrieving Results for Index 19: El Paso.
Looking for El Paso latitude and longitude.
------------
Retrieving Results for Index 20: Detroit.
Looking for Detroit latitude and longitude.
------------
Retrieving Results for Index 21: Washington.
Looking for Washington latitude and longitude.
------------
Retrieving Results for Index 22: Boston.
Looking for Boston latitude and longitude.
------------
Retrieving Results for Index 23: Memphis.
Looking for Memphis latitude and longitude.
------------
Retrieving Results for Index 24: Nashville.
Looking for Nashville latitude and longitude.
------------
Retrieving Results for Index 25: Portland.
Looking for Portland latitude and longitude.
------------
Retrieving Results for Index 26: Oklahoma City.
Looking for Oklahoma City latitude and longitude.
------------
Retrieving Results for Index 27: Las Vegas.
Looking for Las Vegas latitude and longitude.
------------
Retrieving Results for Index 28: Baltimore.
Looking for Baltimore latitude and longitude.
------------
Retrieving Results for Index 29: Louisville.
Looking for Louisville latitude and longitude.
------------
Retrieving Results for Index 30: Milwaukee.
Looking for Milwaukee latitude and longitude.
------------
Retrieving Results for Index 31: Albuquerque.
Looking for Albuquerque latitude and longitude.
------------
Retrieving Results for Index 32: Tucson.
Looking for Tucson latitude and longitude.
------------
Retrieving Results for Index 33: Fresno.
Looking for Fresno latitude and longitude.
------------
Retrieving Results for Index 34: Sacramento.
Looking for Sacramento latitude and longitude.
------------
Retrieving Results for Index 35: Kansas City.
Looking for Kansas City latitude and longitude.
------------
Retrieving Results for Index 36: Long Beach.
Looking for Long Beach latitude and longitude.
------------
Retrieving Results for Index 37: Mesa.
Looking for Mesa latitude and longitude.
------------
Retrieving Results for Index 38: Atlanta.
Looking for Atlanta latitude and longitude.
------------
Retrieving Results for Index 39: Colorado Springs.
Looking for Colorado Springs latitude and longitude.
------------
Retrieving Results for Index 40: Virginia Beach.
Looking for Virginia Beach latitude and longitude.
------------
Retrieving Results for Index 41: Raleigh.
Looking for Raleigh latitude and longitude.
------------
Retrieving Results for Index 42: Omaha.
Looking for Omaha latitude and longitude.
------------
Retrieving Results for Index 43: Miami.
Looking for Miami latitude and longitude.
------------
Retrieving Results for Index 44: Oakland.
Looking for Oakland latitude and longitude.
------------
Retrieving Results for Index 45: Minneapolis.
Looking for Minneapolis latitude and longitude.
------------
Retrieving Results for Index 46: Tulsa.
Looking for Tulsa latitude and longitude.
------------
Retrieving Results for Index 47: Wichita.
Looking for Wichita latitude and longitude.
------------
Retrieving Results for Index 48: New Orleans.
Looking for New Orleans latitude and longitude.
------------
Retrieving Results for Index 49: Arlington.
Looking for Arlington latitude and longitude.
------------
Retrieving Results for Index 50: Cleveland.
Looking for Cleveland latitude and longitude.
------------
Retrieving Results for Index 51: Bakersfield.
Looking for Bakersfield latitude and longitude.
------------
Retrieving Results for Index 52: Tampa.
Looking for Tampa latitude and longitude.
------------
Retrieving Results for Index 53: Aurora.
Looking for Aurora latitude and longitude.
------------
Retrieving Results for Index 54: Honolulu.
Looking for Honolulu latitude and longitude.
------------
Retrieving Results for Index 55: Anaheim.
Looking for Anaheim latitude and longitude.
------------
Retrieving Results for Index 56: Santa Ana.
Looking for Santa Ana latitude and longitude.
------------
Retrieving Results for Index 57: Corpus Christi.
Looking for Corpus Christi latitude and longitude.
------------
Retrieving Results for Index 58: Riverside.
Looking for Riverside latitude and longitude.
------------
Retrieving Results for Index 59: St. Louis.
Looking for St. Louis latitude and longitude.
------------
Retrieving Results for Index 60: Lexington.
Looking for Lexington latitude and longitude.
------------
Retrieving Results for Index 61: Stockton.
Looking for Stockton latitude and longitude.
------------
Retrieving Results for Index 62: Pittsburgh.
Looking for Pittsburgh latitude and longitude.
------------
Retrieving Results for Index 63: Saint Paul.
Looking for Saint Paul latitude and longitude.
------------
Retrieving Results for Index 64: Anchorage.
Looking for Anchorage latitude and longitude.
------------
Retrieving Results for Index 65: Cincinnati.
Looking for Cincinnati latitude and longitude.
------------
Retrieving Results for Index 66: Henderson.
Looking for Henderson latitude and longitude.
------------
Retrieving Results for Index 67: Greensboro.
Looking for Greensboro latitude and longitude.
------------
Retrieving Results for Index 68: Plano.
Looking for Plano latitude and longitude.
------------
Retrieving Results for Index 69: Newark.
Looking for Newark latitude and longitude.
------------
Retrieving Results for Index 70: Toledo.
Looking for Toledo latitude and longitude.
------------
Retrieving Results for Index 71: Lincoln.
Looking for Lincoln latitude and longitude.
------------
Retrieving Results for Index 72: Orlando.
Looking for Orlando latitude and longitude.
------------
Retrieving Results for Index 73: Chula Vista.
Looking for Chula Vista latitude and longitude.
------------
Retrieving Results for Index 74: Jersey City.
Looking for Jersey City latitude and longitude.
------------
Retrieving Results for Index 75: Chandler.
Looking for Chandler latitude and longitude.
------------
Retrieving Results for Index 76: Fort Wayne.
Looking for Fort Wayne latitude and longitude.
------------
Retrieving Results for Index 77: Buffalo.
Looking for Buffalo latitude and longitude.
------------
Retrieving Results for Index 78: Durham.
Looking for Durham latitude and longitude.
------------
Retrieving Results for Index 79: St. Petersburg.
Looking for St. Petersburg latitude and longitude.
------------
Retrieving Results for Index 80: Irvine.
Looking for Irvine latitude and longitude.
------------
Retrieving Results for Index 81: Laredo.
Looking for Laredo latitude and longitude.
------------
Retrieving Results for Index 82: Lubbock.
Looking for Lubbock latitude and longitude.
------------
Retrieving Results for Index 83: Madison.
Looking for Madison latitude and longitude.
------------
Retrieving Results for Index 84: Gilbert.
Looking for Gilbert latitude and longitude.
------------
Retrieving Results for Index 85: Norfolk.
Looking for Norfolk latitude and longitude.
------------
Retrieving Results for Index 86: Reno.
Looking for Reno latitude and longitude.
------------
Retrieving Results for Index 87: Winston-Salem.
Looking for Winston-Salem latitude and longitude.
------------
Retrieving Results for Index 88: Glendale.
Looking for Glendale latitude and longitude.
------------
Retrieving Results for Index 89: Hialeah.
Looking for Hialeah latitude and longitude.
------------
Retrieving Results for Index 90: Garland.
Looking for Garland latitude and longitude.
------------
Retrieving Results for Index 91: Scottsdale.
Looking for Scottsdale latitude and longitude.
------------
Retrieving Results for Index 92: Irving.
Looking for Irving latitude and longitude.
------------
Retrieving Results for Index 93: Chesapeake.
Looking for Chesapeake latitude and longitude.
------------
Retrieving Results for Index 94: North Las Vegas.
Looking for North Las Vegas latitude and longitude.
------------
Retrieving Results for Index 95: Fremont.
Looking for Fremont latitude and longitude.
------------
Retrieving Results for Index 96: Baton Rouge.
Looking for Baton Rouge latitude and longitude.
------------
Retrieving Results for Index 97: Richmond.
Looking for Richmond latitude and longitude.
------------
Retrieving Results for Index 98: Boise.
Looking for Boise latitude and longitude.
------------
Retrieving Results for Index 99: San Bernardino.
Looking for San Bernardino latitude and longitude.
------------

In [10]:
cities_pd.head()
# Use the lat/lng we recovered to identify airports
# Hint: Code is similar to above block (i.e. you will need to use cities_pd.iterrows() again)
# Hint: Use the keyword search for "international+airport"
# Hint: Use a try-except to handle airports that are missing ratings

,City,State,lat,lng,airport name,airport address,airport rating
0,New York City,New York,40.7128,-74.006,,,
1,Los Angeles,California,34.0522,-118.244,,,
2,Chicago,Illinois,41.8781,-87.6298,,,
3,Houston,Texas,29.7604,-95.3698,,,
4,Philadelphia,Pennsylvania,39.9526,-75.1652,,,

In [1]:
# Save Data to csv


# Visualize to confirm airport data appears